# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
- {name: 'Events', url: "#events"}
- {name: 'Projects', url: '#projects'}
- {name: 'About Us', url: '#about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/Open-Uptown'}
- {icon: 'meetup', link: 'https://www.meetup.com/openuptown'}
- {icon: 'slack', link: 'https://uptown-codes.herokuapp.com/'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'envelope', link: 'mailto:Open-Uptown@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
